version: 0.2

env:
  git-credential-helper: yes

environment_variables:
  plaintext:
    AWS_DEFAULT_REGION: "eu-west-1"
    HUGO_VERSION: "0.62"

phases:
  install:
    runtime-versions:
        golang: 1.13
    commands:
      - echo "Entered the install phase..."
      - curl -s -L https://github.com/gohugoio/hugo/releases/download/v0.62.2/hugo_0.62.2_Linux-64bit.deb -o hugo.deb
      - dpkg -i hugo.deb
    finally:
      - echo "Installation done"
    
  build:
    commands:
      - echo "Entered the build phase ..."
      - echo "Build started on `date`"
      - sh scripts/codebuild-git-wrapper.sh https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/www.lonbergit.co.uk master
      - git log | head -100
      - hugo -v
    finally:
      - echo "Building the HTML files finished"
      - ls -la public
  post_build:
    command:
      - echo "Entering post-build phase"
      - zip -qr dev.zip public/*
    finally:
      - echo "Files zipped and post-build complete"

artifacts:
  files:
    - '**/*'
  base-directory: $CODEBUILD_SRC_DIR/public/
  discard-paths: no  