version: 0.1

environment_variables:
  plaintext:
    AWS_DEFAULT_REGION: "eu-west-1"
    HUGO_VERSION: "0.26"
    HUGO_SHA256: "67e4ba5ec2a02c8164b6846e30a17cc765b0165a5b183d5e480149baf54e1a50"

phases:
  install:
    commands:
      - sudo apt-get install tree
      - wget https://github.com/gohugoio/hugo/releases/download/v0.26/hugo_0.26_Linux-64bit.deb
      - dpkg -i hugo_0.26_Linux-64bit.deb
    
  build:
    commands:
      - hugo -v --log
      - sleep 10
      - ls -la public
      - tree
      
  post_build:
    commands:
      - aws s3 sync --delete public s3://lonbergit.co.uk --cache-control max-age=3600